### PR TITLE
Index french

### PR DESCRIPTION
**Pull request by madiodio**
Trying to contribute to the translation into french. Doing my best to tackle the remaining pages.

### CODE REVIEW

**Comment by xtuc** [comment]
Thanks for your PR :+1: 

It seems you added the files in 97a43fefe2d750efd251d2e62e044a561bccddaf but removed them in 3aa2650e8b9bb97fd826ff356675ecc69d6aba55.

Did you rebase with Preact's repo? Where does the others commits come from?

**Comment by madiodio** [comment]
I started translating 2 files in the **about** folder and then realize i was in the **index-branch** which I supposed deals only with the index file right? That's why I removed them from this commit https://github.com/xtuc/preact-www/commit/3aa2650e8b9bb97fd826ff356675ecc69d6aba55 and commit only the index in https://github.com/xtuc/preact-www/commit/97a43fefe2d750efd251d2e62e044a561bccddaf. But anyway I'm creating two branches for the **about** and **guide** pages I don't know if i'm doing right but no I did'nt rebase with Preact'repo.

**Comment by xtuc** [comment]
Yes, I did create a separate branch for the page, easier to manage.

Could you create theses branch (from master) with your translated files? We can then close this PR.

Thanks.

**Comment by madiodio** [comment]
Yes that's what I was thinking of. We can close it, thanks.

**Pull request closed without merging**
